name: Update OTel Collector Dependencies and Generate OTel Agent

on:
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:

jobs:
  update-and-generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version-file: .python-version
          cache: 'pip'

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: .go-version

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Collector Update Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          inv -e install-tools
          inv -e collector.update
          inv -e collector.generate
          inv -e generate-licenses
          inv -e collector.pull-request
